image: docker:latest

variables:
  GIT_STRATEGY: clone
  
services:
    - docker:dind

stages:
    - build
    - deploy

before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD nexus.budg.bars.group

build:
    stage: build
    only:
        - master
    script:
        - docker build -t nexus.budg.bars.group/databaser:latest .
    tags:
        - gitlab-databaser

deploy:
    stage: deploy
    only:
        - master

    script:
        - docker push nexus.budg.bars.group/databaser:latest
    tags:
        - gitlab-databaser